title: Theoretical CS
description: >-
  This is the class website for Theoretical CS.
#Site settings
excerpt_length: 55

include: ['units']

#Build settings
markdown: kramdown
permalink: pretty
future: true